---
title: "KaylaWilliams_A3"
author: "Kayla Williams"
date: "10/14/2021"
output: html_document
---

```{r}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

```{r}
#FS = Food Stamps, 1 = Yes 
#FPARC = Family Presence and Age of Related Children 
#1 = With related children under 5 years only
#GRPIP = Gross rent as a percentage of household income past #12 months
#For housing costs to be considered affordable, these total #costs should not exceed 30 percent of household income, #according to the US Department of Housing and Urban #Development. Households paying more than 30 percent of #income toward housing are #considered housing “cost-burdened,” and those with housing costs that exceed #half of #income are considered “severely” cost-burdened.
#https://calbudgetcenter.org/resources/throughout-the-state-californians-pay-more-than-they-can-afford-for-housing/

pums_2019_1yr <- getCensus(
  name = "acs/acs1/pums",
  vintage = 2019,
  region = "public use microdata area:*", 
  regionin = "state:06",
  vars = c(
    "SERIALNO",
    "SPORDER",
    "PWGTP",
    "WGTP",
    "HINCP",
    "FS", 
    "FPARC",
    "GRPIP"
  )
)
```
```{r}
saveRDS(pums_2019_1yr, "pums_2019_1yr.rds")
pums2019 = readRDS("pums_2019_1yr.rds")
```
```{r}
ca_pumas =
  pumas("CA", cb = T, progress_bar = F)

bay_county_names =
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties =
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

bay_pums <-
  pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% bay_pumas$PUMACE10)
```

```{r}
bay_pums_example <-
  bay_pums %>% 
  filter(SPORDER == 1) %>% 
  mutate(
    WGTP = as.numeric(WGTP),
    lo_income = ifelse(
      (FS == 1 | GRPIP > 30),
      1,
      0
      )
  ) %>% 
  group_by(PUMA) %>% 
  summarize(
    sum_lo_income =
      sum(lo_income, na.rm =T)
  ) %>% 
  left_join(
    bay_pumas %>% 
      select(PUMACE10),
    by = c("PUMA" = "PUMACE10")
  ) %>% 
  st_as_sf()
```

```{r}
pums_pal <- colorNumeric(
  palette = "Oranges",
  domain = bay_pums_example$sum_lo_income
)

leaflet() %>%
  addTiles() %>% 
  addPolygons(
    data = bay_pums_example,
    fillColor = ~pums_pal(sum_lo_income),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste(
      (sum_lo_income), 
      "# recieving food stamps or housing cost burdended"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = bay_pums_example,
    pal = pums_pal,
    values = ~sum_lo_income,
    title = "# recieving food stamps or housing cost burdended"
  )

```